apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: razglednica-z-visa
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: razglednica-z-visa
    newName: rg.fr-par.scw.cloud/djnd/razglednica-z-visa
    newTag: 'latest'
